// Code generated by MockGen. DO NOT EDIT.
// Source: book.go

// Package mock_persistence is a generated GoMock package.
package mock_persistence

import (
	context "context"
	reflect "reflect"
	model "server/api/domain/model"
	persistence "server/api/infrastracture/persistence"

	gomock "github.com/golang/mock/gomock"
)

// MockBookRepositoryInterface is a mock of BookRepositoryInterface interface.
type MockBookRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryInterfaceMockRecorder
}

// MockBookRepositoryInterfaceMockRecorder is the mock recorder for MockBookRepositoryInterface.
type MockBookRepositoryInterfaceMockRecorder struct {
	mock *MockBookRepositoryInterface
}

// NewMockBookRepositoryInterface creates a new mock instance.
func NewMockBookRepositoryInterface(ctrl *gomock.Controller) *MockBookRepositoryInterface {
	mock := &MockBookRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRepositoryInterface) EXPECT() *MockBookRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookRepositoryInterface) Create(arg0 context.Context, arg1 persistence.RepositoryInterface, arg2 *model.Book) (*model.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBookRepositoryInterfaceMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookRepositoryInterface)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockBookRepositoryInterface) Delete(arg0 context.Context, arg1 persistence.RepositoryInterface, arg2 *model.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookRepositoryInterfaceMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookRepositoryInterface)(nil).Delete), arg0, arg1, arg2)
}

// FindAll mocks base method.
func (m *MockBookRepositoryInterface) FindAll(ctx context.Context, ri persistence.RepositoryInterface) ([]*model.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, ri)
	ret0, _ := ret[0].([]*model.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBookRepositoryInterfaceMockRecorder) FindAll(ctx, ri interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBookRepositoryInterface)(nil).FindAll), ctx, ri)
}

// FindByUUID mocks base method.
func (m *MockBookRepositoryInterface) FindByUUID(arg0 context.Context, arg1 persistence.RepositoryInterface, arg2 string) (*model.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUUID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUUID indicates an expected call of FindByUUID.
func (mr *MockBookRepositoryInterfaceMockRecorder) FindByUUID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUUID", reflect.TypeOf((*MockBookRepositoryInterface)(nil).FindByUUID), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockBookRepositoryInterface) Update(arg0 context.Context, arg1 persistence.RepositoryInterface, arg2 *model.Book) (*model.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBookRepositoryInterfaceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookRepositoryInterface)(nil).Update), arg0, arg1, arg2)
}
